const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');

router.get('/dashboard', adminController.getDashboard); 
router.get('/api/appointments', adminController.getAppointments); 
router.get('/api/earnings', adminController.getEarnings); 
router.get('/api/signins', adminController.getSignins);
router.get('/form', adminController.getForm);  
router.post('/login',adminController.login);
router.post('/signup',adminController.signup);
router.get('/users',adminController.getUsers);
router.delete('/users/:type/:id',adminController.deleteUser);
router.get('/profile', adminController.getProfile); 
router.get('/edit-profile', adminController.getEditProfile); 
router.post('/update-profile', adminController.updateProfile);
router.get('/profile-data', adminController.getProfileData);
router.get('/api/finance', adminController.getFinanceData); 
router.get('/api/earnings', adminController.getEarnings); 
router.get('/api/revenue-summary', adminController.getRevenueSummary); 
router.get('/search-data', adminController.getSearchData);
module.exports = router;