const express = require('express');
const router = express.Router();
const patientController = require('../controllers/patientController');
const medicineController = require('../controllers/medicineController');
// modifed patient routes for appointment cancellation
router.get('/dashboard', patientController.getDashboard); 
router.post('/signup', patientController.signup); 
router.post('/login', patientController.login); 
router.get('/profile', patientController.getProfile); 
router.get('/edit-profile', patientController.getEditProfile); 
router.post('/update-profile', patientController.updateProfile); 
router.get('/form', patientController.getForm); 
router.get('/book-appointment', patientController.getBookAppointment); 
router.get('/book-doc-online', patientController.getBookDocOnline); 
router.get('/doctor-profile-patient/:id', patientController.getDoctorProfilePatient); 
router.get('/order-medicines', patientController.getOrderMedicines); 
router.post('/api/add-to-cart', patientController.postAddToCart); 
router.get('/api/doctors/online', patientController.getDoctorsOnline); 
router.get('/api/doctors/offline', patientController.getDoctorsOffline); 
router.get('/api/doctors/all', patientController.getDoctorsAll); 
router.get('/api/medicines/search', patientController.getMedicinesSearch);
router.get('/medicines/:id', medicineController.getDetail); 
router.get('/api/patient/appointments/previous',patientController.getPreviousAppointments);
router.get('/api/patient/appointments/upcoming',patientController.getUpcomingAppointments); 
router.get('/prescriptions', patientController.getPrescriptions);
router.get('/prescriptions/download/:id', patientController.downloadPrescription);
router.get('/profile-data', patientController.getProfileData);
module.exports = router;
